name: Update README cards
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=radical
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&bg_color=24283b&title_color=7aa2f7&icon_color=bb9af7&text_color=c0caf5&border_color=565f89
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&bg_color=24283b&title_color=7aa2f7&text_color=c0caf5&border_color=565f89
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
